### ISSUE TITLE
Better bluetooth audio quality bug

### ISSUE THREAD

**Issue by RealGohan** [oSumAtrIX/aliucord-plugins#1]
Whenever I recconect to a vc with the plugin the audio is only coming from one ear and without the plugin both ears work perfectly

**Comment by oSumAtrIX** [comment]
Have you tried another headset and did you use bluetooth or cable?

**Comment by RealGohan** [comment]
> Have you tried another headset and did you use bluetooth or cable?

I used bluetooth and yes I tried another headset I am havin the same problem with all of them

**Comment by flleeppyy** [comment]
selecting audio outputs straight up just doesn't work. it only comes out the earpiece

**Comment by oSumAtrIX** [comment]
This is something I can but did not implement yet. The method which is needed for that to work is directly connected to what is causing the decrease in audio quality. It is definitely something, which I want to work on, but do not have enough time to invest in. As of now, turning off the plugin and rejoining a channel if necessary is a temporal fix to change the audio output source. Otherwise, I am happy for any PR and if I have time, I will fix this issue asap.

**Comment by oSumAtrIX** [comment]
Fixed
